### PR TITLE
Update to 1.9.0-beta1

### PR DESCRIPTION
**Pull request by bitwiseman**
1.9.0 will be out soon.  

It addresses a number of line wrapping issues (such as https://github.com/beautify-web/js-beautify/issues/1324).   If we can update this plugin to 1.9.0-beta1, it will give the next release a lot of good testing.

### CODE REVIEW

**Comment by bitwiseman** [comment]
I'm clear why this failed.  Any help would be appreciated.

**Comment by aeschli** [comment]
Thanks a lot @bitwiseman, I'll merge on Monday for the January Build

**Comment by bitwiseman** [comment]
@aeschli 
Excellent, thanks.  This is pretty major change.  
If you have any time to run some manual tests on it, that would be much appreciated.

**Comment by bitwiseman** [comment]
@aeschli  Here's some highlights you can use for the release: 
https://github.com/beautify-web/js-beautify/releases/tag/v1.9.0-beta4

**Pull request merged**
