### PR TITLE
Update js-beautify to 1.8.0-rc4

### PR DESCRIPTION
**Pull request by bitwiseman**
@aeschli  
1.8.0-rc4 Fixes several breaking bugs in 1.8.0-rc2.  In particular https://github.com/beautify-web/js-beautify/issues/1464 - where element casing was not being preserved.  

Please consider taking this update.

### CODE REVIEW

**Comment by aeschli** [comment]
@bitwiseman Thanks a lot!

**Comment by aeschli** [comment]
@bitwiseman Should I surface wrapAttributes: 'aligned-multiple' and `wrapAttributesIndentSize`, or do you plan to replace these very soon?
Also, I couldn't find a compact description of what `aligned-multiple` does...

**Comment by bitwiseman** [comment]
You should go ahead and add the new options and values.  We won't be
replacing them in the short term.

As to the description, "attributes that wrap will align vertically ,
multiple attributes are allowed per line".

**Comment by aeschli** [comment]
Thanks a lot! I'll surface the new settings ASAP.

**Pull request merged**
